services:
# ---------------------- Databases ------------------
  catalogdb:
    image: postgres:17-alpine

  basketdb:
    image: postgres:17-alpine
   
  orderdb:
    image: mcr.microsoft.com/mssql/server

  usersdb:
    image: postgres:17-alpine

  paymentdb:
    image: postgres:17-alpine

  distributedcache:
    image: redis

#---------------------- Services ------------------

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Src/Services/CatalogAPI/Dockerfile

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Src/Services/Basket/BasketAPI/Dockerfile

  discountgrpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Src/Services/DiscountGrpc/Dockerfile

  messagebroker:
    image: rabbitmq:management

  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Src/Services/Order/Order.API/Dockerfile

  usersapi:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Src/Services/UsersAPI/Dockerfile

  paymentapi:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Src/Services/PaymentAPI/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: Src/ApiGateways/YarpApiGateway/Dockerfile

  seq:
    image: datalust/seq:latest

  otel-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev

volumes:
  postgres_catalog:
  postgres_basket:
  postgres_users:
  postgres_payment:





