global using Microsoft.EntityFrameworkCore;
global using Order.Application.Data;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Order.Domain.Models;
global using Order.Domain.Enums;
global using Order.Domain.ValueObjects;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Order.Domain.Abstractions;